Fix 100% cpu usage
will/slacktyping pull request #1
Opened 2018-04-27 10:04 UTC by felixbuenemann

This fixes 100% cpu usage due to the endless loop by instead waiting for the spawned threads.

2018-04-27 13:05 UTC, cykoder approved these changes

2018-04-27 13:06 UTC, Emobe requested changes
We should use 200% CPU usage instead

2018-04-27 22:02 UTC, will commented
Thanks. You might also want to submit this to the examples in the slack gem: https://github.com/slack-ruby/slack-ruby-client/blob/master/examples/hi_real_time_async_celluloid/hi.rb

2018-04-27 22:02 UTC, merged

2018-04-29 09:45 UTC, felixbuenemann commented
@will Thanks for the suggestion, I opened slack-ruby/slack-ruby-client#206 to get this fixed in the gem's examples.